iprt/Makefile.kmk: Added a test-mangling rule.
git-svn-id: http://www.virtualbox.org/svn/vbox/trunk@36488 cfe28804-0f27-0410-a406-dd0f0b0b656f

diff --git a/src/VBox/Runtime/Makefile.kmk b/src/VBox/Runtime/Makefile.kmk
--- a/src/VBox/Runtime/Makefile.kmk
+++ b/src/VBox/Runtime/Makefile.kmk
@@ -2211,6 +2211,26 @@ test-doxygen::
 	@echo $(DOXYGEN_OUTPUT_PREV)
 	@echo $(IPRT_DOXYFILE_INPUT)
 
+test-mangling:: $(RuntimeR3_1_TARGET)
+ifn1of ($(KBUILD_TARGET),win)
+	rcExit=0; \
+	for fn in ` nm $(RuntimeR3_1_TARGET) \
+			| $(SED) -n \
+				-e 's/^[0-9a-f][0-9a-f]* //' \
+				-e '/^[TUD]/!d' \
+				-e 's/^. //' \
+				-e '/^RT/p' \
+				-e '/^g_/p' `; \
+	do \
+		if $(SED) -ne '/\#define '"$${fn}"' /q 1' $(PATH_ROOT)/include/iprt/mangling.h; then \
+			echo "mangling.h: Missing '"$${fn}"'"; \
+			rcExit=1;\
+		fi \
+	done; \
+	exit $${rcExit}
+endif
+
+
 #
 # Generate the rules (we're the to sub-makefile).
 #
