configure: for internal builds on Linux insist on OpenWatcom
git-svn-id: https://www.virtualbox.org/svn/vbox/trunk@67684 cfe28804-0f27-0410-a406-dd0f0b0b656f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -544,7 +544,11 @@ check_open_watcom()
   if [ -z "$WATCOM" ]; then
     WATCOM=`/bin/ls -rd1 $PWD/tools/common/openwatcom/* 2> /dev/null | head -1`
     if [ -z "$WATCOM" ]; then
-      log_failure "Open Watcom was not found"
+      if [ $OSE -eq 0 -a $OS = "linux" ]; then
+        log_failure "Open Watcom was not found"
+        exit 1
+      fi
+      log_failure "Open Watcom was not found, using alternative BIOS sources"
       cnf_append "VBOX_WITH_OPEN_WATCOM" ""
       return 0;
     fi
