FE/Qt: Qt5 migration (part 93): Preparing Qt5 tool: X11: Qt5 tuning for configure script.
git-svn-id: https://www.virtualbox.org/svn/vbox/trunk@59681 cfe28804-0f27-0410-a406-dd0f0b0b656f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -81,6 +81,7 @@ WITH_VMMRAW=1
 WITH_LIBIDL=1
 WITH_GSOAP=0
 WITH_QT4=1
+WITH_QT5=0
 WITH_SDL=1
 WITH_SDL_TTF=1
 WITH_X11=1
@@ -153,6 +154,8 @@ PKGCONFIG="`which_wrapper pkg-config`"
 PYTHONDIR="/usr /usr/local"
 QT4DIR="/usr/lib/qt4 /usr/share/qt4 /usr/lib64/qt4 /usr /usr/local"
 QT4DIR_PKGCONFIG=1
+QT5DIR="/usr/lib/qt5 /usr/share/qt5 /usr/lib64/qt5 /usr /usr/local"
+QT5DIR_PKGCONFIG=1
 KBUILDDIR="`cd \`dirname $0\`; pwd`/kBuild"
 DEVDIR="`cd \`dirname $0\`; pwd`/tools"
 if [ -d "/lib/modules/`uname -r`/build" ]; then
@@ -286,8 +289,8 @@ test_compile()
   echo "compiling the following source file:" >> $LOG
   cat $ODIR.tmp_src.cc >> $LOG
   echo "using the following command line:" >> $LOG
-  echo "$CXX $CXX_FLAGS -g -O -Wall -o $ODIR.tmp_out $ODIR.tmp_src.cc \"$1\"" >> $LOG
-  $CXX $CXX_FLAGS -g -O -Wall -o $ODIR.tmp_out $ODIR.tmp_src.cc $1 >> $LOG 2>&1
+  echo "$CXX $CXX_FLAGS -fPIC -g -O -Wall -o $ODIR.tmp_out $ODIR.tmp_src.cc \"$1\"" >> $LOG
+  $CXX $CXX_FLAGS -fPIC -g -O -Wall -o $ODIR.tmp_out $ODIR.tmp_src.cc $1 >> $LOG 2>&1
   if [ $? -ne 0 ]; then
     if [ -z "$4" ]; then
       echo
@@ -1499,7 +1502,7 @@ EOF
       LIBQT4=-F$PATH_SDK_QT4/Frameworks
       FLGQT4="-framework QtCore"
     else
-      log_failure "Qt4 framework not found (can be disabled using --disable-qt4)"
+      log_failure "Qt4 framework not found (can be disabled using --disable-qt)"
       fail
     fi
   else # !darwin
@@ -1620,6 +1623,179 @@ EOF
     fi
   else
     log_failure "qt4 not found"
+    fail
+  fi
+}
+
+
+#
+# Check for the Qt5 library, needed by the VirtualBox frontend
+#
+# Currently not fatal.
+#
+check_qt5()
+{
+  foundqt5=
+  test_header Qt5
+  cat > $ODIR.tmp_src.cc << EOF
+#include <QtGlobal>
+extern "C" int main(void)
+{
+#if QT_VERSION >= 0x050501
+  return 0;
+#else
+  return 1;
+#endif
+}
+EOF
+  if [ "$OS" = "darwin" ]; then
+    # First check if there is the internal version of Qt. If yes nothing else
+    # has to be done.
+    QT_INTERNAL=`/bin/ls -rd1 $PWD/tools/$BUILD_TARGET.$BUILD_PLATFORM_ARCH/qt/* 2> /dev/null`
+    for t in $QT_INTERNAL; do
+      if [ -f "$t/Frameworks/QtCoreVBox.framework/QtCoreVBox" ]; then
+        cnf_append "VBOX_WITH_ORACLE_QT" "1"
+        log_success "use internal version"
+        return
+      fi
+    done
+    # Now try the user provided directory and some of the standard directories.
+    QT_TRIES="$QT5DIR /System/Library /Library"
+    for t in $QT_TRIES; do
+      if [ -f "$t/Frameworks/QtCore.framework/QtCore" ]; then
+        PATH_SDK_QT5="$t"
+        break
+      fi
+    done
+    # Add the necessary params for building the test application
+    if [ -n "$PATH_SDK_QT5" ]; then
+      foundqt5=1
+      INCQT5=-I$PATH_SDK_QT5/Frameworks/QtCore.framework/Headers
+      LIBQT5=-F$PATH_SDK_QT5/Frameworks
+      FLGQT5="-framework QtCore"
+    else
+      log_failure "Qt5 framework not found (can be disabled using --disable-qt)"
+      fail
+    fi
+  else # !darwin
+    if [ $QT5DIR_PKGCONFIG -eq 1 ]; then
+      # Default is to use pkg-config:
+      if which_wrapper pkg-config > /dev/null; then
+        qt5_ver=`pkg-config Qt5Core --modversion 2>> $LOG`
+        if [ $? -eq 0 ]; then
+          FLGQT5=`pkg-config Qt5Core --cflags`
+          INCQT5=`strip_I "$FLGQT5"`
+          LIBDIR5=`pkg-config Qt5Core --variable=libdir`
+          LIBQT5=`pkg-config Qt5Core --libs`
+          LIBQT5="-L$LIBDIR5 $LIBQT5"
+          TOOLQT5=`pkg-config Qt5Core --variable=prefix`
+          TOOLQT5BIN=`pkg-config Qt5Core --variable=host_bins`
+          if test_compile "$LIBQT5 $LIBPTHREAD $I_INCQT5 $FLGQT5" qt5 qt5 nofatal; then
+            test_execute_path "`strip_L "$LIBQT5"`" nofatal && foundqt5=3 # pkg-config
+          fi
+        fi
+      else
+        log_failure "pkg-config not found"
+        fail
+      fi
+    fi
+    if [ -z "$foundqt5" ]; then
+      # Do it the old way (e.g. user has specified QT5DIR):
+      for q in $QT5DIR "$PWD/tools/linux.$TARGET_MACHINE"/qt/v5.*; do
+        INCQT5="$q/include $q/include/QtCore"
+        FLGQT5="-DQT_SHARED"
+        I_INCQT5=`prefix_I "$INCQT5"`
+        LIBQT5="-L$q/lib -lQt5CoreVBox"
+        TOOLQT5="$q"
+        if test_compile "$LIBQT5 $LIBPTHREAD $I_INCQT5 $FLGQT5" qt5 qt5 nofatal &&
+            test_execute_path "`strip_L "$LIBQT5"`" nofatal; then
+          foundqt5=2 # internal
+          break;
+        fi
+        LIBQT5="-L$q/lib -lQt5Core"
+        if test_compile "$LIBQT5 $LIBPTHREAD $I_INCQT5 $FLGQT5" qt5 qt5 nofatal &&
+            test_execute_path "`strip_L "$LIBQT5"`" nofatal; then
+          foundqt5=1 # no pkg-config, Qt directory
+          break;
+        fi
+      done
+    fi
+  fi
+  if [ -n "$foundqt5" ]; then
+    # We decided which version of Qt to use, now enforce the version requirement:
+    cat > $ODIR.tmp_src.cc << EOF
+#include <cstdio>
+#include <QtGlobal>
+extern "C" int main(void)
+{
+  printf("found version %s", QT_VERSION_STR);
+#if QT_VERSION >= 0x050501
+  printf(", OK.\n");
+  return 0;
+#else
+  printf(", expected version 5.5.1 or higher\n");
+  return 1;
+#endif
+}
+EOF
+    [ -n "$INCQT5" ] && I_INCQT5=`prefix_I "$INCQT5"`
+    if test_compile "$LIBQT5 $LIBPTHREAD $I_INCQT5 $FLGQT5" qt5 qt5 nofatal; then
+      if test_execute_path "`strip_L "$LIBQT5"`"; then
+        if [ "$OS" = "darwin" ]; then
+          # Successful build & run the test application so add the necessary
+          # params to AutoConfig.kmk:
+          cnf_append "PATH_SDK_QT5_INC" "$PATH_SDK_QT5/Frameworks"
+          cnf_append "PATH_SDK_QT5_LIB" "$PATH_SDK_QT5/Frameworks"
+          cnf_append "PATH_SDK_QT5" "$PATH_SDK_QT5/Frameworks"
+          # Check for the moc tool in the Qt directory found & some standard
+          # directories.
+          for q in $PATH_SDK_QT5 /usr /Developer/Tools/Qt; do
+            if which_wrapper "$q/bin/moc" > /dev/null; then
+              cnf_append "PATH_TOOL_QT5_BIN" "$q/bin"
+            fi
+          done
+        else
+          # Strip .../QtCore as we add components ourself:
+          INCQT5=`echo "$INCQT5"|$KBUILD_SED 's|\([^ ]*\)/QtCore|\1|g; s| $||g'`
+          # store only the first path, remove all other paths
+          # most likely pkg-config gave us -I/usr/include/qt5 -I/usr/include/qt5/QtCore
+          INCQT5=`echo "$INCQT5"|$KBUILD_SED 's|\([^ ]*\) .*|\1|'`
+          cnf_append "VBOX_PATH_QT_LIB" "`strip_L "$LIBQT5"`"
+          cnf_append "PATH_SDK_QT5_INC" "$INCQT5"
+          # This is not quite right since the qt libpath does not have to be first...
+          cnf_append "PATH_SDK_QT5_LIB" '$'"(firstword `strip_L "$LIBQT5"`)"
+          if [ "$foundqt5" = "2" ]; then
+            cnf_append "VBOX_WITH_ORACLE_QT" "1"
+          fi
+          if [ "$foundqt5" != "3" ]; then
+            TOOLQT5BIN="$TOOLQT5/bin"
+          fi
+          test_header "Qt5 devtools"
+          # Try it with a suffix, some platforms use that
+          if which_wrapper "$TOOLQT5BIN/moc-qt5" > /dev/null; then
+            QT5BINSUFF="-qt5"
+          else
+            QT5BINSUFF=""
+          fi
+          moc_ver=`$TOOLQT5BIN/moc$QT5BINSUFF -v 2>&1|sed 's+^.*(Qt \(.*\))+\1+'`
+          if [ $? -ne 0 ]; then
+            log_failure "moc$QT5BINSUFF not working"
+            fail
+          else
+            log_success "found version $moc_ver"
+            cnf_append "VBOX_PATH_QT" "$TOOLQT5"
+            cnf_append "PATH_SDK_QT5" "$TOOLQT5"
+            cnf_append "PATH_TOOL_QT5_BIN" "$TOOLQT5BIN"
+            [ -n "$QT5BINSUFF" ] && cnf_append "TOOL_QT5_BIN_SUFF" "$QT5BINSUFF"
+          fi
+        fi
+      fi
+    else
+      log_failure "qt5 not working"
+      fail
+    fi
+  else
+    log_failure "qt5 not found"
     fail
   fi
 }
@@ -2277,11 +2453,15 @@ EOF
 [ $WITH_JAVA    -eq 1 ] && echo "  --disable-java           disable java bindings"
 [ $WITH_VMMRAW  -eq 1 ] && echo "  --disable-vmmraw         disable VMM raw mode (VT-x/AMD-V mandatory!)"
 [ $WITH_SDL_TTF -eq 1 ] && echo "  --disable-sdl-ttf        disable SDL_ttf detection"
+[ $WITH_QT4     -eq 1 ] && echo "  --disable-qt             disable Qt detection"
+[ $WITH_QT5     -eq 1 ] && echo "  --disable-qt             disable Qt detection"
 [ $WITH_ALSA    -eq 1 ] && echo "  --disable-alsa           disable the ALSA sound backend"
 [ $WITH_PULSE   -eq 1 ] && echo "  --disable-pulse          disable the PulseAudio backend"
 [ $WITH_DBUS    -eq 1 ] && echo "  --disable-dbus           don't use DBus and hal for hardware detection"
 [ $WITH_KMODS   -eq 1 ] && echo "  --disable-kmods          don't build Linux kernel modules (host and guest)"
 [ $WITH_OPENGL  -eq 1 ] && echo "  --disable-opengl         disable OpenGL support (2D & 3D)"
+[ $WITH_QT4     -eq 0 ] && echo "  --enable-qt4             enable Qt4 detection"
+[ $WITH_QT5     -eq 0 ] && echo "  --enable-qt5             enable Qt5 detection"
 [ $WITH_GSOAP   -eq 0 ] && echo "  --enable-webservice      enable the webservice stuff"
 [ $OSE          -eq 1 ] && echo "  --enable-vnc             enable the VNC server"
 [ $OSE          -eq 0 ] && echo "  --disable-extpack        don't build the extpack"
@@ -2315,7 +2495,8 @@ EOF
 [ "$OS"   = "darwin" ] && echo "                           contains OS X 10.6 SDK (required for Mountain Lion and newer hosts"
 [ "$OS"   = "darwin" ] && echo "                           only, ignored for the rest)"
 [ "$OS"    = "linux" ] && echo "  --with-linux=DIR         Linux kernel source directory [$LINUX]"
-[ $WITH_QT4    -eq 1 ] && echo "  --with-qt-dir=DIR        directory for Qt4 headers/libraries [pkgconfig]"
+[ $WITH_QT4    -eq 1 ] && echo "  --with-qt-dir=DIR        directory for Qt headers/libraries [pkgconfig]"
+[ $WITH_QT5    -eq 1 ] && echo "  --with-qt-dir=DIR        directory for Qt headers/libraries [pkgconfig]"
 [ $WITH_GSOAP  -eq 1 ] && echo "  --with-gsoap-dir=PATH    directory for gSOAP compiler/headers/libraries"
 [ $WITH_GSOAP  -eq 1 ] && echo "                           (soapcpp2 and wsdl2h, soapstd2.h, libgsoap++.a/so)"
 [ $WITH_GSOAP  -eq 1 ] && echo "  --with-gsoap-import=PATH directory for gSOAP import files (stlvector.h)"
@@ -2407,9 +2588,11 @@ for option in "$@"; do
         exit 1
       fi
       ;;
-    --with-qt-dir=*|--with-qt4-dir=*)
-      QT4DIR=`echo $option | cut -d'=' -f2`
-      QT4DIR_PKGCONFIG=0
+    --with-qt-dir=*)
+      [ $WITH_QT4 -eq 1 ] && QT4DIR=`echo $option | cut -d'=' -f2`
+      [ $WITH_QT4 -eq 1 ] && QT4DIR_PKGCONFIG=0
+      [ $WITH_QT5 -eq 1 ] && QT5DIR=`echo $option | cut -d'=' -f2`
+      [ $WITH_QT5 -eq 1 ] && QT5DIR_PKGCONFIG=0
       ;;
     --with-openssl-dir=*)
       OPENSSLDIR=`echo $option | cut -d'=' -f2`
@@ -2461,8 +2644,14 @@ for option in "$@"; do
       ;;
     --disable-qt)
       [ $WITH_QT4 -eq 1 ] && WITH_QT4=0
+      [ $WITH_QT5 -eq 1 ] && WITH_QT5=0
       ;;
-    --disable-qt4)
+    --enable-qt4)
+      [ $WITH_QT4 -eq 0 ] && WITH_QT4=1
+      [ $WITH_QT5 -eq 1 ] && WITH_QT5=0
+      ;;
+    --enable-qt5)
+      [ $WITH_QT5 -eq 0 ] && WITH_QT5=1
       [ $WITH_QT4 -eq 1 ] && WITH_QT4=0
       ;;
     --passive-mesa)
@@ -2544,6 +2733,7 @@ for option in "$@"; do
       WITH_X11=0
       WITH_OPENGL=0
       WITH_QT4=0
+      WITH_QT5=0
       ;;
     --ose)
       OSE=2
@@ -2690,7 +2880,8 @@ if [ $WITH_OPENGL -eq 0 ]; then
   cnf_append "VBOX_GUI_USE_QGL" ""
 fi
 [ $WITH_XPCOM     -eq 0 ] && cnf_append "VBOX_WITH_MAIN" ""
-[ $WITH_QT4       -eq 0 ] && cnf_append "VBOX_WITH_QTGUI" ""
+[ $WITH_QT4       -eq 0 -a $WITH_QT5       -eq 0 ] && cnf_append "VBOX_WITH_QTGUI" ""
+[ $WITH_QT5       -eq 1 ] && cnf_append "VBOX_WITH_QTGUI_V5" "1"
 [ $WITH_SDL_TTF   -eq 0 ] && cnf_append "VBOX_WITH_SECURELABEL" ""
 [ $WITH_PYTHON    -eq 0 ] && cnf_append "VBOX_WITH_PYTHON" ""
 [ $WITH_JAVA      -eq 0 ] && cnf_append "VBOX_WITH_JXPCOM" ""
@@ -2740,6 +2931,7 @@ if [ $ONLY_ADDITIONS -eq 0 ]; then
   [ $WITH_X11    -eq 1 ] && check_xrandr
   [ $WITH_OPENGL -eq 1 ] && check_opengl
   [ $WITH_QT4    -eq 1 ] && check_qt4
+  [ $WITH_QT5    -eq 1 ] && check_qt5
   [ $WITH_PYTHON -eq 1 ] && check_python
   [ $WITH_JAVA   -eq 1 ] && check_java
 
