configure: improved detection of Qt4
git-svn-id: http://www.virtualbox.org/svn/vbox/trunk@7470 cfe28804-0f27-0410-a406-dd0f0b0b656f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -63,7 +63,9 @@ INCZ=""
 LIBZ="-lz"
 INCPNG=""
 LIBPNG="-lpng"
-QTDIR="/usr/qt/3 /usr/lib/qt3 /usr/lib/qt-3.3 /usr/share/qt3 /usr/lib64/qt-3.3 /usr/X11R6 /usr/lib/qt"
+QT3DIR="/usr/qt/3 /usr/lib/qt3 /usr/lib/qt-3.3 /usr/share/qt3 /usr/lib64/qt-3.3 /usr/X11R6 /usr/lib/qt"
+QT4DIR="/usr/lib/qt4 /usr/share/qt4 /usr"
+QT4UIC3DIR="/usr/bin"
 KBUILDDIR="`cd \`dirname $0\`; pwd`/kBuild"
 DEVDIR="`cd \`dirname $0\`; pwd`/tools"
 if [ -d "/lib/modules/`uname -r`/build" ]; then
@@ -1083,7 +1085,7 @@ EOF
 }
 
 #
-# Check for the QT library, needed by VirtualBox
+# Check for the Qt3 library, needed by VirtualBox
 #
 check_qt3()
 {
@@ -1108,7 +1110,7 @@ EOF
   found_qt=0
   libs="lib"
   [ "$LIB" = "lib64" ] && libs="$libs lib64"
-  for q in $QTDIR; do
+  for q in $QT3DIR; do
     for l in $libs; do
       echo "compiling the following source file:" >> $LOG
       cat .tmp_src.cc >> $LOG
@@ -1117,7 +1119,7 @@ EOF
       $CXX -O -Wall -o .tmp_out .tmp_src.cc -I$q/include -L$q/$l -lqt-mt $LIBPTHREAD >> $LOG 2>&1
       if [ $? -eq 0 ]; then
         if test_execute; then
-          cnf_append "QTDIR" "`cd $q ; pwd`"
+          cnf_append "QT3DIR" "`cd $q ; pwd`"
           found_qt=1
           break
         fi
@@ -1129,13 +1131,13 @@ EOF
   done
   if [ $found_qt -ne 1 ]; then
     echo
-    echo "  Qt not found at \"$QTDIR\" or Qt headers not found"
+    echo "  Qt3 not found at \"$QT3DIR\" or Qt3 headers not found"
     echo "  Check the file $LOG for detailed error information."
     fail
     return 1
   fi
-  test_header "Qt devtools"
-  if check_avail "$q/bin/moc" QTDIR/bin; then
+  test_header "Qt3 devtools"
+  if check_avail "$q/bin/moc" QT3DIR/bin; then
     moc_ver=`$q/bin/moc 2>&1 -v|sed 's+^.*(Qt \(.*\))+\1+'`
     if [ $? -ne 0 ]; then
       log_failure "not found"
@@ -1147,7 +1149,7 @@ EOF
 }
 
 #
-# Check for the QT library, needed by VirtualBox4
+# Check for the Qt4 library, needed by VirtualBox4
 #
 # Currently not fatal.
 #
@@ -1169,13 +1171,10 @@ check_qt4()
 extern "C" int main(void)
 {
   printf("found version %s", QT_VERSION_STR);
-#if QT_VERSION >= 0x030305
+#if QT_VERSION >= 0x040200
   printf(", OK.\n");
   return 0;
-#elif QT_VERSION >= 0x030300
-  printf("\n  ** WARNING: QT < 3.3.5 has known problems!\n");
-#else
-  printf(", expected version 3.3.0 or higher\n");
+  printf(", expected version 4.2.0 or higher\n");
   return 1;
 #endif
 }
@@ -1183,13 +1182,41 @@ EOF
       [ -n "$INCQT4" ] && I_INCQT4=`prefix_I "$INCQT4"`
       if test_compile "$LIBQT4 $LIBPTHREAD $I_INCQT4" qt4 qt4 nofatal; then
         if test_execute; then
-          cnf_append "SDK_VBOX_LIBQT4_INCS" "$INCQT4"
-          cnf_append "SDK_VBOX_LIBQT4_LIBS" "`strip_l "$LIBQT4"`"
+#          cnf_append "SDK_VBOX_LIBQT4_INCS" "$INCQT4"
+#          cnf_append "SDK_VBOX_LIBQT4_LIBS" "`strip_l "$LIBQT4"`"
+          test_header "Qt4 devtools"
+          for q in $QT4DIR; do
+            if which_wrapper "$q/bin/moc" > /dev/null; then
+              moc_ver=`$q/bin/moc -v 2>&1|sed 's+^.*(Qt \(.*\))+\1+'`
+              if [ $? -ne 0 ]; then
+                log_failure "not found"
+                fail
+              else
+                log_success "found version $moc_ver"
+                cnf_append "VBOX_PATH_QT4" "$q"
+                test_header "Qt4 uic3"
+                for q in $QT4UIC3DIR; do
+                  if check_avail "$q/uic3" QT4UIC3DIR; then
+                    uic3_ver=`$q/uic3 -version 2>&1|sed 's+^.*version \(.*\)+\1+'`
+                    if [ $? -ne 0 ]; then
+                      log_failure "not found"
+                      fail
+                    else
+                      log_success "found version $uic3_ver"
+                      cnf_append "VBOX_UIC3" "$q/uic3"
+                    fi
+                  fi
+                done
+              fi
+              break
+            fi
+          done
         fi
       fi
     fi
   else
     log_failure "pkg-config not found"
+#    not yet
 #    fail
   fi
 }
@@ -1428,7 +1455,8 @@ Paths:
   --with-iasl=PATH         location of the iasl compiler [$IASL]
   --with-linux=DIR         Linux kernel source directory [$LINUX]
   --with-mkisofs=PATH      location of mkisofs [$MKISOFS]
-  --with-qt-dir=DIR        directory for QT headers/libraries [$QTDIR]
+  --with-qt-dir=DIR        directory for Qt3 headers/libraries [$QT3DIR]
+  --with-qt4-dir=DIR       directory for Qt4 headers/libraries [$QT4DIR]
 
 Build type:
   -d, --build-debug        build with debugging symbols and assertions
@@ -1466,7 +1494,10 @@ for option in $*; do
       fi
       ;;
     --with-qt-dir=*)
-      QTDIR=`echo $option | cut -d'=' -f2`
+      QT3DIR=`echo $option | cut -d'=' -f2`
+      ;;
+    --with-qt4-dir=*)
+      QT4DIR=`echo $option | cut -d'=' -f2`
       ;;
     --with-iasl=*)
       IASL=`echo $option | cut -d'=' -f2`
