VPX: allow to build against libvpx provided by the build system
git-svn-id: http://www.virtualbox.org/svn/vbox/trunk@45772 cfe28804-0f27-0410-a406-dd0f0b0b656f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -98,6 +98,7 @@ WITH_DOCS=1
 BUILD_LIBXML2=
 BUILD_LIBCURL=
 BUILD_LIBSSL=
+BUILD_LIBVPX=
 PASSIVE_MESA=0
 CC="gcc"
 CC32=""
@@ -1624,6 +1625,57 @@ EOF
   fi
 }
 
+#
+# Check for libvpx
+#
+check_vpx()
+{
+  if [ -z "$BUILD_LIBVPX" ]; then
+    test_header libvpx
+    if which_wrapper pkg-config > /dev/null; then
+      libvpx_ver=`pkg-config vpx --modversion 2>> $LOG`
+      if [ $? -ne 0 ]; then
+        log_failure "libvpx not found"
+        fail
+      else
+        FLGVPX=`pkg-config vpx --cflags`
+        INCVPX=`strip_I "$FLGVPX"`
+        LIBVPX=`pkg-config vpx --libs`
+    cat > $ODIR.tmp_src.cc << EOF
+#include <cstdio>
+#include <vpx/vpx_codec.h>
+extern "C" int main(void)
+{
+  int version = vpx_codec_version();
+  int verMajor = VPX_VERSION_MAJOR(version);
+  int verMinor = VPX_VERSION_MINOR(version);
+  int verPatch = VPX_VERSION_PATCH(version);
+  printf("found version %d.%d.%d", verMajor, verMinor, verPatch);
+  if (verMajor == 1 && verMinor >= 0)
+  {
+      printf(", OK.\n");
+      return 0;
+  }
+  else
+  {
+      printf(", expected version 1.0.0 or higher\n");
+      return 1;
+   }
+}
+EOF
+        [ -n "$INCVPX" ] && I_INCVPX=`prefix_I "$INCVPX"`
+        if test_compile "$LIBVPX $LIBPTHREAD $I_INCVPX" vpx vpx; then
+          if test_execute; then
+            cnf_append "SDK_VBOX_VPX_INCS" "$INCVPX"
+            cnf_append "SDK_VBOX_VPX_LIBS" "`strip_l "$LIBVPX"`"
+          fi
+        fi
+      fi
+    fi
+  fi
+}
+
+
 
 #
 # Check whether static libstdc++ is installed. This library is required
@@ -2192,6 +2244,7 @@ EOF
 [ $OSE -eq 0 ] && cat << EOF
   --build-libssl           build openssl from sources
   --build-libcurl          build libcurl from sources
+  --build-libvpx           build libvpx from sources
 EOF
 [ "$OS"   != "darwin" ] && echo "  --setup-wine             setup a Wine directory and register the hhc hack"
 cat << EOF
@@ -2246,6 +2299,7 @@ if [ "$OS" = "darwin" ]; then
   WITH_DBUS=0
   WITH_KMODS=0
   BUILD_LIBXML2=1
+  BUILD_LIBVPX=1
   [ $OSE -eq 1 ] || BUILD_LIBCURL=1
 elif [ "$OS" = "haiku" ]; then
   #WITH_SDL=0
@@ -2407,6 +2461,9 @@ for option in $*; do
       ;;
     --build-libcurl)
       BUILD_LIBCURL=1
+      ;;
+    --build-libvpx)
+      BUILD_LIBVPX=1
       ;;
     --build-headless)
       HEADLESS=1
@@ -2584,6 +2641,7 @@ check_libxml2
 [ $WITH_LIBIDL -eq 1 ] && check_libidl
 check_ssl
 check_curl
+check_vpx
 [ "$OS" != "darwin"  ] && check_z
 [ "$OS" != "darwin"  ] && check_png
 [ $OSE -eq 0 -a "$OS" = "linux" ] && check_pam
