configure: allow a different out directory on Linux build hosts
git-svn-id: http://www.virtualbox.org/svn/vbox/trunk@16257 cfe28804-0f27-0410-a406-dd0f0b0b656f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -49,6 +49,9 @@ which_wrapper()
 #
 OSE=1
 ODIR="`pwd`/"
+ODIR_OVERRIDE=0
+OUT_PATH=""
+OUT_PATH_OVERRIDE=0
 SETUP_WINE=
 TARGET_MACHINE=""
 TARGET_CPU=""
@@ -1725,6 +1728,8 @@ Paths:
   --with-mkisofs=PATH      location of mkisofs [$MKISOFS]
   --with-qt-dir=DIR        directory for Qt4 headers/libraries [pkgconfig]
   --with-gsoap-dir=PATH    directory for SOAP compiler (soapcpp2 and wsdl2h)
+  --out-path=PATH          the folder to which configuration and build output
+                           should go
 
 Build type:
   -d, --build-debug        build with debugging symbols and assertions
@@ -1840,6 +1845,24 @@ for option in $*; do
       ;;
     --odir=*)
       ODIR="`echo $option | cut -d'=' -f2`/"
+      ODIR_OVERRIDE=1
+      ;;
+    --out-path=*)
+      out_path="`echo $option | cut -d'=' -f2`/"
+      if [ -d $out_path ]; then
+        saved_path="`pwd`"
+        cd $out_path
+        OUT_PATH="`pwd`/"
+        cd $saved_path
+        OUT_PATH_OVERRIDE=1
+        if [ $ODIR_OVERRIDE -eq 0 ]; then
+          # This variable has not *yet* been overridden.  That can still happen.
+          ODIR=$OUT_PATH
+        fi
+      else
+        echo "Error: invalid folder \"$out_path\" in option \"$option\""
+        exit 1
+      fi
       ;;
     --setup-wine)
       SETUP_WINE=1
@@ -1911,6 +1934,13 @@ check_kbuild
 # append the tools directory to the default search path
 echo "$PATH" | grep -q "$DEVDIR_BIN" || PATH="$PATH:$DEVDIR_BIN"
 export PATH
+
+# if we will be writing to a different out directory then set this up now
+if [ $OUT_PATH_OVERRIDE -eq 1 ]; then
+  echo "export AUTOCFG=$OUT_PATH""AutoConfig.kmk" >> $ENV
+  echo "export LOCALCFG=$OUT_PATH""LocalConfig.kmk" >> $ENV
+  echo "export PATH_OUT_BASE=$OUT_PATH" >> $ENV
+fi
 
 # some things are not available in for OSE
 if [ $OSE -ge 1 ]; then
@@ -2030,9 +2060,14 @@ echo "  source $ENV"
 echo "  kmk"
 echo ""
 if [ "$OS" = "linux" ]; then
+    if [ $OUT_PATH_OVERRIDE -eq 1 ]; then
+      vbox_out_path=$OUT_PATH
+    else
+      vbox_out_path=./out/
+    fi
     echo "To compile the kernel module, do:"
     echo ""
-    echo "  cd ./out/$OS.$TARGET_MACHINE/$BUILD_TYPE/bin/src/vboxdrv"
+    echo "  cd $vbox_out_path$OS.$TARGET_MACHINE/$BUILD_TYPE/bin/src/vboxdrv"
     echo "  make"
     echo ""
 fi
