IPRT,Drivers: Committed a modified version of the diff_linux_guest_host patch. This mangles the IPRT symbols in kernel space on linux and later other platforms.
git-svn-id: http://www.virtualbox.org/svn/vbox/trunk@36190 cfe28804-0f27-0410-a406-dd0f0b0b656f

diff --git a/src/VBox/Additions/common/VBoxGuest/linux/Makefile b/src/VBox/Additions/common/VBoxGuest/linux/Makefile
--- a/src/VBox/Additions/common/VBoxGuest/linux/Makefile
+++ b/src/VBox/Additions/common/VBoxGuest/linux/Makefile
@@ -270,7 +270,7 @@ MODULE_EXT := ko
 $(MODULE)-y  := $(OBJS)
 
 # build defs
-EXTRA_CFLAGS += $(INCL) $(KFLAGS) $(KDEBUG)
+EXTRA_CFLAGS += -include $(KBUILD_EXTMOD)/include/VBox/VBoxGuestMangling.h  $(INCL) $(KFLAGS) $(KDEBUG)
 
 all: $(MODULE)
 
@@ -287,6 +287,14 @@ install: $(MODULE)
 	PATH="$(PATH):/bin:/sbin" depmod -a;
 
 endif # eq($(MAKECMDGOALS),clean)
+
+check: $(MODULE)
+	@if ! readelf -p __ksymtab_strings vboxguest.ko | grep -E "\[.*\]  *(RT|g_..*RT.*)"; then \
+	    echo "All exported IPRT symbols are properly renamed!"; \
+	 else \
+	    echo "error: Some exported IPRT symbols was not properly renamed! See above." >&2; \
+	    false; \
+	 fi
 
 clean:
 	for f in . linux r0drv generic r0drv/linux r0drv/generic VBox \
diff --git a/src/VBox/HostDrivers/Support/linux/Makefile b/src/VBox/HostDrivers/Support/linux/Makefile
--- a/src/VBox/HostDrivers/Support/linux/Makefile
+++ b/src/VBox/HostDrivers/Support/linux/Makefile
@@ -262,7 +262,7 @@ MODULE_EXT    := ko
 $(MODULE)-y   := $(OBJS)
 
 # build defs
-EXTRA_CFLAGS  += $(INCL) $(KFLAGS) $(KDEBUG)
+EXTRA_CFLAGS  += -include $(KBUILD_EXTMOD)/include/VBox/SUPDrvMangling.h $(INCL) $(KFLAGS) $(KDEBUG)
 
 all: $(MODULE)
 
@@ -303,3 +303,12 @@ clean:
  endif
 
 endif # eq($(MAKECMDGOALS),clean)
+
+check: $(MODULE)
+	@if ! readelf -p __ksymtab_strings vboxdrv.ko | grep -E "\[.*\]  *(RT|g_..*RT.*)"; then \
+	    echo "All exported IPRT symbols are properly renamed!"; \
+	 else \
+	    echo "error: Some exported IPRT symbols was not properly renamed! See above." >&2; \
+	    false; \
+	 fi
+
