OS X installer: more checks for preinstall and postflight scripts.
git-svn-id: https://www.virtualbox.org/svn/vbox/trunk@47366 cfe28804-0f27-0410-a406-dd0f0b0b656f

diff --git a/src/VBox/Installer/darwin/VirtualBox/postflight b/src/VBox/Installer/darwin/VirtualBox/postflight
--- a/src/VBox/Installer/darwin/VirtualBox/postflight
+++ b/src/VBox/Installer/darwin/VirtualBox/postflight
@@ -16,12 +16,6 @@ CP="/bin/cp -f"
 CPDIR="${CP} -R"
 
 #
-# Correct the ownership of the directories in case there
-# was an existing installation.
-#
-chown -R root:admin /Applications/VirtualBox.app
-
-#
 # Select the right architecture.
 #
 MY_ARCH=`uname -m`
@@ -90,10 +84,22 @@ if [[ -e "${LSREGISTER}" && "x" != "x${USER}" ]]; then
     /usr/bin/sudo -u "${USER}" ${LSREGISTER} -f /Applications/VirtualBox.app/Contents/Resources/vmstarter.app
 fi
 
+# Check environment.
+if [ "${INSTALLER_TEMP}x" == "x" ]; then
+    echo "Required environment variable INSTALLER_TEMP is missing. Aborting installation."
+    exit 1;
+fi
+
 # Restore previously installed Extension Packs (if any)
 if [ -d "${INSTALLER_TEMP}/ExtensionPacks" ]; then
     cp -r "${INSTALLER_TEMP}/ExtensionPacks" "${VBOX_INSTALL_PATH}"
     rm -rf "${INSTALLER_TEMP}/ExtensionPacks"
 fi
+
+#
+# Correct the ownership of the directories in case there
+# was an existing installation.
+#
+chown -R root:admin /Applications/VirtualBox.app
 
 exit 0;
diff --git a/src/VBox/Installer/darwin/VirtualBox/preinstall b/src/VBox/Installer/darwin/VirtualBox/preinstall
--- a/src/VBox/Installer/darwin/VirtualBox/preinstall
+++ b/src/VBox/Installer/darwin/VirtualBox/preinstall
@@ -12,6 +12,14 @@
 # hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
 #
 
+set -e
+
+# Check environment.
+if [ "${INSTALLER_TEMP}x" == "x" ]; then
+    echo "Required environment variable INSTALLER_TEMP is missing. Aborting installation."
+    exit 1;
+fi
+
 # Backup previously installed Extension Packs before
 # installation process will completely remove previously installed
 # VirtualBox distribution.
