sync debian/ directory
git-svn-id: http://www.virtualbox.org/svn/vbox/trunk@5739 cfe28804-0f27-0410-a406-dd0f0b0b656f

diff --git a/debian/vboxnet.init.tmpl b/debian/vboxnet.init.tmpl
--- a/debian/vboxnet.init.tmpl
+++ b/debian/vboxnet.init.tmpl
@@ -112,6 +112,13 @@ start_network() {
     if ! VBoxTunctl -h 2>&1 | grep -q VBoxTunctl > /dev/null; then
       failure "VBoxTunctl not found"
     fi
+    # Fail if we don't have the kernel tun device
+    # Make sure that the tun module is loaded (Ubuntu 7.10 needs this)
+    modprobe tun > /dev/null 2>&1
+    if ! cat /proc/misc 2>/dev/null | grep tun > /dev/null
+    then
+      failure "Linux tun/tap subsystem not available"
+    fi
     # Read the configuration file entries line by line and create the
     # interfaces
     while read line; do
