debian-ose: sync vboxdrv.init.in
git-svn-id: http://www.virtualbox.org/svn/vbox/trunk@7515 cfe28804-0f27-0410-a406-dd0f0b0b656f

diff --git a/debian/vboxdrv.init.in b/debian/vboxdrv.init.in
--- a/debian/vboxdrv.init.in
+++ b/debian/vboxdrv.init.in
@@ -1,7 +1,7 @@
-#! /bin/bash
-#
+#! /bin/sh
 # innotek VirtualBox
 # Linux kernel module init script
+
 #
 # Copyright (C) 2006-2007 innotek GmbH
 #
@@ -13,7 +13,6 @@
 # VirtualBox OSE distribution. VirtualBox OSE is distributed in the
 # hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
 #
-
 
 # chkconfig: 35 30 60
 # description: VirtualBox Linux kernel module
@@ -27,153 +26,288 @@
 # Short-Description: VirtualBox Linux kernel module
 ### END INIT INFO
 
-KDIR="/lib/modules/`uname -r`/misc"
+PATH=/sbin:/bin:/usr/sbin:/usr/bin:$PATH
 DEVICE=/dev/vboxdrv
 MODNAME=vboxdrv
 GROUPNAME=vboxusers
 LOG="/var/log/vbox-install.log"
 NOLSB=%NOLSB%
 
-if [ -r /etc/default/virtualbox-ose ]; then
-  . /etc/default/virtualbox-ose
+[ -f /lib/lsb/init-functions ] || NOLSB=yes
+[ -f /etc/vbox/vbox.cfg ] && . /etc/vbox/vbox.cfg
+
+if [ -n "$INSTALL_DIR" ]; then
+    VBOXMANAGE="$INSTALL_DIR/VBoxManage"
+    BUILDINTMP="$INSTALL_DIR/src/build_in_tmp"
+else
+    VBOXMANAGE="/usr/lib/virtualbox-ose/VBoxManage"
+    BUILDINTMP="/usr/share/virtualbox-ose/src/build_in_tmp"
 fi
 
-if [ -z "$NOLSB" -a -f /lib/lsb/init-functions ]; then
-  . /lib/lsb/init-functions
+if [ -n "$NOLSB" ]; then
+    if [ -f /etc/redhat-release ]; then
+        system=redhat
+    elif [ -f /etc/SuSE-release ]; then
+        system=suse
+    elif [ -f /etc/gentoo-release ]; then
+        system=gentoo
+    fi
+fi
+
+[ -r /etc/default/virtualbox-ose ] && . /etc/default/virtualbox-ose
+
+if [ -z "$NOLSB" ]; then
+    . /lib/lsb/init-functions
+    fail_msg() {
+        echo ""
+        log_failure_msg "$1"
+    }
+    succ_msg() {
+        log_success_msg " done."
+    }
+    begin_msg() {
+        log_daemon_msg "$@"
+    }
 else
-  log_daemon_msg()
-  {
-    if [ -z "${1:-}" ]; then
-      return 1
-    fi
-    if [ -z "${2:-}" ]; then
-      echo -n "$1:"
-      return
-    fi
-    echo -n "$1: $2"
-  }
-  log_end_msg()
-  {
-    [ -z "${1:-}" ] && return 1
-    if [ $1 -eq 0 ]; then
-      echo "."
+    if [ "$system" = "redhat" ]; then
+        . /etc/init.d/functions
+        fail_msg() {
+            echo -n " "
+            echo_failure
+            echo
+            echo "  ($1)"
+        }
+        succ_msg() {
+            echo -n " "
+            echo_success
+            echo
+        }
+    elif [ "$system" = "suse" ]; then
+        . /etc/rc.status
+        fail_msg() {
+            rc_failed 1
+            rc_status -v
+            echo "  ($1)"
+        }
+        succ_msg() {
+            rc_reset
+            rc_status -v
+        }
+    elif [ "$system" = "gentoo" ]; then
+        . /sbin/functions.sh
+        fail_msg() {
+            eerror "$1"
+        }
+        succ_msg() {
+            eend "$?"
+        }
+        begin_msg() {
+            ebegin "$1"
+        }
+        if [ "`which $0`" = "/sbin/rc" ]; then
+            shift
+        fi
     else
-      echo " failed!"
+        fail_msg() {
+            echo " ...failed!"
+            echo "  ($1)"
+        }
+        succ_msg() {
+            echo " ...done."
+        }
     fi
-  }
-  log_success_msg()
-  {
-    echo "$@"
-  }
-  log_failure_msg()
-  {
-    echo "$@"
-  }
+    if [ "$system" != "gentoo" ]; then
+        begin_msg() {
+            [ -z "${1:-}" ] && return 1
+            if [ -z "${2:-}" ]; then
+                echo -n "$1"
+            else
+                echo -n "$1: $2"
+            fi
+        }
+    fi
 fi
 
 failure()
 {
-  echo ""
-  log_failure_msg "$1"
-  exit 0
+    fail_msg "$1"
+    exit 0
 }
 
 running()
 {
-  lsmod | grep -q "$MODNAME[^_-]"
+    lsmod | grep -q "$MODNAME[^_-]"
 }
 
 start()
 {
-  log_daemon_msg "Starting VirtualBox kernel module" "$MODNAME";
-  # ensure the module is loaded
-  if ! running; then
-    if [ ! -f "$KDIR/$MODNAME.o" -a ! "$KDIR/$MODNAME.ko" ]; then
-      failure "No suitable module for running kernel found."
+    begin_msg "Starting VirtualBox kernel module"
+    if ! running; then
+        if ! find /lib/modules/`uname -r` -name "vboxdrv\.*" 2>/dev/null|grep -q vboxdrv; then
+            failure "No suitable module for running kernel found"
+        fi
+        if ! rm -f $DEVICE; then
+            failure "Cannot remove $DEVICE"
+        fi
+        if ! modprobe $MODNAME > /dev/null 2>&1; then
+            failure "modprobe $MODNAME failed. Please use 'dmesg' to find out why"
+        fi
+        sleep .2
     fi
-    if ! modprobe $MODNAME > /dev/null 2>&1; then
-      failure "Modprobe $MODNAME failed. Please use 'dmesg' to find out why."
+    # ensure the character special exists
+    if [ ! -c $DEVICE ]; then
+        MAJOR=`sed -n 's;\([0-9]\+\) vboxdrv;\1;p' /proc/devices`
+        if [ ! -z "$MAJOR" ]; then
+            MINOR=0
+        else
+            MINOR=`sed -n 's;\([0-9]\+\) vboxdrv;\1;p' /proc/misc`
+            if [ ! -z "$MINOR" ]; then
+                MAJOR=10
+            fi
+        fi
+        if [ -z "$MAJOR" ]; then
+            rmmod $MODNAME 2>/dev/null
+            failure "Cannot locate the VirtualBox device"
+        fi
+        if ! mknod -m 0660 $DEVICE c $MAJOR $MINOR 2>/dev/null; then
+            rmmod $MODNAME 2>/dev/null
+            failure "Cannot create device $DEVICE with major $MAJOR and minor $MINOR"
+        fi
     fi
-    sleep .2
-  fi
-  # ensure the character special exists
-  if [ ! -c $DEVICE ]; then
-    MAJOR=`sed -n 's;\([0-9]\+\) vboxdrv;\1;p' /proc/devices`
-    if [ -n "$MAJOR" ]; then
-      MINOR=0
-    else
-      MINOR=`sed -n 's;\([0-9]\+\) vboxdrv;\1;p' /proc/misc`
-      if [ -n "$MINOR" ]; then
-        MAJOR=10
-      fi
+    # ensure permissions
+    if ! chown :$GROUPNAME $DEVICE 2>/dev/null; then
+        rmmod $MODNAME 2>/dev/null
+        failure "Cannot change owner $GROUPNAME for device $DEVICE"
     fi
-    if [ -z "$MAJOR" ]; then
-      rmmod $MODNAME
-      failure "Cannot locate device major."
-    fi
-    if ! mknod -m 0660 $DEVICE c $MAJOR $MINOR; then
-      rmmod $MODNAME
-      failure "Cannot create device $DEVICE with major $MAJOR and minor $MINOR."
-    fi
-  fi
-  # ensure permissions
-  if ! chown :$GROUPNAME $DEVICE; then
-    rmmod $MODNAME
-    failure "Cannot change owner $GROUPNAME for device $DEVICE."
-  fi
-  log_end_msg 0
+    succ_msg
 }
 
 stop()
 {
-  log_daemon_msg "Stopping VirtualBox kernel module" "$MODNAME";
-  killall -q VBoxSVC
-  if running; then
-    if ! rmmod $MODNAME 2>/dev/null; then
-      failure "Cannot unload module $MODNAME."
+    begin_msg "Stopping VirtualBox kernel module"
+    if running; then
+        if ! rmmod $MODNAME 2>/dev/null; then
+            failure "Cannot unload module $MODNAME"
+        fi
+        if ! rm -f $DEVICE; then
+            failure "Cannot unlink $DEVICE"
+        fi
     fi
-    if ! rm -f $DEVICE; then
-      failure "Cannot unlink $DEVICE."
+    succ_msg
+}
+
+# enter the following variables in /etc/default/virtualbox-ose:
+#   SHUTDOWN_USERS="foo bar"  
+#     check for running VMs of user foo and user bar
+#   SHUTDOWN=poweroff
+#   SHUTDOWN=acpibutton
+#   SHUTDOWN=savestate
+#     select one of these shutdown methods for running VMs
+stop_vms()
+{
+    wait=0
+    for i in $SHUTDOWN_USERS; do
+        # don't create the ipcd directory with wrong permissions!
+        if [ -d /tmp/.vbox-$i-ipc ]; then
+            export VBOX_IPC_SOCKETID="$i"
+            VMS=`$VBOXMANAGE -nologo list runningvms 2>/dev/null`
+            if [ -n "$VMS" ]; then
+                if [ "$SHUTDOWN" = "poweroff" ]; then
+                    begin_msg "Powering off remaining VMs"
+                    for v in $VMS; do
+                        $VBOXMANAGE -nologo controlvm $v poweroff
+                    done
+                    succ_msg
+                elif [ "$SHUTDOWN" = "acpibutton" ]; then
+                    begin_msg "Sending ACPI power button event to remaining VMs"
+                    for v in $VMS; do
+                        $VBOXMANAGE -nologo controlvm $v acpipowerbutton
+                        wait=30
+                    done
+                    succ_msg
+                elif [ "$SHUTDOWN" = "savestate" ]; then
+                    begin_msg "Saving state of remaining VMs"
+                    for v in $VMS; do
+                        $VBOXMANAGE -nologo controlvm $v savestate
+                    done
+                    succ_msg
+                fi
+            fi
+        fi
+    done
+    # wait for some seconds when doing ACPI shutdown
+    if [ "$wait" -ne 0 ]; then
+        begin_msg "Waiting for $wait seconds for VM shutdown"
+        sleep $wait
+        succ_msg
     fi
-  fi
-  log_end_msg 0
+}
+
+setup()
+{
+    stop
+    if find /lib/modules/`uname -r` -name "vboxdrv\.*" 2>/dev/null|grep -q vboxdrv; then
+      begin_msg "Removing old VirtualBox kernel module"
+      find /lib/modules/`uname -r` -name "vboxdrv\.*" 2>/dev/null|xargs rm -f 2>/dev/null
+      succ_msg
+    fi
+    begin_msg "Recompiling VirtualBox kernel module"
+    if ! $BUILDINTMP install > $LOG 2>&1; then
+        failure "Look at $LOG to find out what went wrong"
+    fi
+    succ_msg
+    start
+}
+
+dmnstatus()
+{
+    if running; then
+        echo "VirtualBox kernel module is loaded."
+        for i in $SHUTDOWN_USERS; do
+            # don't create the ipcd directory with wrong permissions!
+            if [ -d /tmp/.vbox-$i-ipc ]; then
+                export VBOX_IPC_SOCKETID="$i"
+                VMS=`$VBOXMANAGE -nologo list runningvms 2>/dev/null`
+                if [ -n "$VMS" ]; then
+                    echo "The following VMs are currently running:"
+                    for v in $VMS; do
+                       echo "  $v"
+                    done
+                fi
+            fi
+        done
+    else
+        echo "VirtualBox kernel module is not loaded."
+    fi
 }
 
 case "$1" in
-  start)
+start)
     start
     ;;
-  stop)
+stop)
+    stop_vms
     stop
     ;;
-  restart|reload|force-reload)
+stop_vms)
+    stop_vms
+    ;;
+restart)
+    stop && start
+    ;;
+force-reload)
     stop
     start
     ;;
-  setup)
-    stop
-    if find /lib/modules/`uname -r` -name "vboxdrv\.*" 2>/dev/null|grep -q vboxdrv; then
-      log_action_begin_msg "Removing old VirtualBox kernel module"
-      find /lib/modules/`uname -r` -name "vboxdrv\.*" 2>/dev/null|xargs rm -f 2>/dev/null
-      log_action_end_msg 0
-    fi
-    log_daemon_msg "Recompiling VirtualBox kernel module" "$MODNAME"
-    if ! /usr/share/virtualbox-ose/src/build_in_tmp install > $LOG 2>&1; then
-      failure "Look at $LOG to find out what went wrong"
-    fi
-    log_end_msg 0
-    start
+setup)
+    setup
     ;;
-  status)
-    if running; then
-      log_success_msg "VirtualBox kernel module is loaded."
-    else
-      log_failure_msg "VirtualBox kernel module is not loaded."
-    fi
+status)
+    dmnstatus
     ;;
-  *)
-    log_failure_msg "Usage: $0 {start|stop|restart|status|setup}"
-    exit 3
+*)
+    echo "Usage: $0 {start|stop|stop_vms|restart|force-reload|status|setup}"
+    exit 1
 esac
 
 exit 0
