Linux installer: silently leave the boot script if the package was deleted but not purged (relevant for Debian/Ubuntu only)
git-svn-id: https://www.virtualbox.org/svn/vbox/trunk@23865 cfe28804-0f27-0410-a406-dd0f0b0b656f

diff --git a/src/VBox/Installer/linux/vboxdrv.sh.in b/src/VBox/Installer/linux/vboxdrv.sh.in
--- a/src/VBox/Installer/linux/vboxdrv.sh.in
+++ b/src/VBox/Installer/linux/vboxdrv.sh.in
@@ -51,6 +51,9 @@ else
     BUILDVBOXNETADP="/usr/share/%PACKAGE%/src/vboxnetadp/build_in_tmp"
 fi
 
+# silently exit if the package was uninstalled but not purged
+[ -x $VBOXMANAGE -a -x $BUILDVBOXDRV ] || exit 0
+
 if [ -n "$NOLSB" ]; then
     if [ -f /etc/redhat-release ]; then
         system=redhat
